version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
      - ./db:/app/db
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    command: sleep infinity 